version: '2'
services:
  phpunit:
    image: gigary/phpunit:5.4.6
    networks:
      - private
    volumes:
      - ./server:/var/www
    links:
      - database
    depends_on:
      - database-restore
    command: phpunit -c /var/www/phpunit.xml
  database-restore:
    image: gigary/mariadb-client:10.1
    networks:
      - private
    volumes:
      - ./data/test.sql:/tmp/db.sql
      - ./data/mysql-import.sh:/tmp/script.sh
    links:
      - database
    depends_on:
      - database
    command: /tmp/script.sh database
  database:
    image: gigary/mariadb:10.1
    networks:
      - private
    expose:
      - 3306
networks:
  private:
    driver: bridge
