version: '2'
services:
  client-nginx:
    image: gigary/nginx:1.8
    networks:
      - private
    restart: always
    volumes:
      - ./client/dist:/var/www
      - ./data/nginx.client.conf:/etc/nginx/nginx.conf
    ports:
      - 30104:80
  server-nginx:
    image: gigary/nginx:1.8
    networks:
      - private
    restart: always
    volumes:
      - ./server:/var/www
      - ./data/nginx.server.conf:/etc/nginx/nginx.conf
    links:
      - server-php:backend
    ports:
      - 30101:80
  server-php:
    image: gigary/php:5.6-dev
    networks:
      - private
    restart: always
    volumes:
      - ./server:/var/www
      - ./data/xdebug.ini:/etc/php5/conf.d/xdebug.ini
    expose:
      - 9000
    links:
      - server-mysql:database
    depends_on:
      - server-mysql-restore
  server-mysql-restore:
    image: gigary/mariadb-client:10.1
    networks:
      - private
    volumes:
      - ./data/prod.sql:/tmp/db.sql
      - ./data/mysql-import.sh:/tmp/script.sh
    links:
      - server-mysql:database
    depends_on:
      - server-mysql
    command: /tmp/script.sh database
  server-mysql:
    image: gigary/mariadb:10.1
    restart: always
    networks:
      - private
    ports:
      - 30102:3306
networks:
  private:
    driver: bridge
